# Generated by Django 4.0.3 on 2022-08-31 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helper',
            name='description',
        ),
        migrations.RemoveField(
            model_name='helper',
            name='title',
        ),
        migrations.AddField(
            model_name='helper',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='helper',
            name='priority',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='helper',
            name='task',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
